#!/usr/bin/env bash
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
Color_Off='\033[0m'       # Text Reset

function installDependency(){
	if [[ -z $(dpkg -l | cut -d " " -f 3 | grep "^$1") ]]; then 
		echo -e "${BRed}\t✗ Installing $1 ${Color_Off}"
		apt --yes install "$1" &> /dev/null; 

	else
		echo -e "${BGreen}\t✓ $1 ${Color_Off}"
	fi
}


function installDependencies(){
	echo -e "${BYellow}Checking dependencies${Color_Off}"
	installDependency "git"
}

installDependencies

tmpDir="/tmp/xcut-`date -u +"%Y%m%d-%H%M%S"`"
mkdir -p "$tmpDir"
cd "$tmpDir"
git clone https://gitlab.com/AbdElraoufSabri/xCut.git &> /dev/null
cd xCut
sudo make
